version: '2'

services:
  solace:
    image: 'docker.io/solace/solace-pubsub-standard:latest'
    ports:
      - '55555:55555'
      - '8082:8080'
    environment:
      - username_admin_globalaccesslevel=admin
      - username_admin_password=admin
      - system_scaling_maxconnectioncount=100
    shm_size: 1g
